package com.example.lomanalyzer.observability

enum class AppEvent {
    APP_STARTED,
    APP_STOPPING,
    SESSION_CREATED,
    DB_MIGRATED,
    ANALYSIS_STARTED,
    ANALYSIS_COMPLETED,
    ANALYSIS_CANCELLED,
    CHECKPOINT_SAVED,
    RETENTION_HARD_DELETE,
    VK_OAUTH_COMPLETED,
    COLLECTION_STARTED,
    COLLECTION_CHECKPOINT,
    COLLECTION_COMPLETED,
    RATE_LIMIT_HIT,
    BACKOFF_APPLIED,
    DISCOVERY_AUTHOR_ADDED,
    PREPROCESSING_STARTED,
    PREPROCESSING_COMPLETED,
    FILTERED_OUT_LANGUAGE,
}
