package com.example.lomanalyzer.storage.tables

import org.jetbrains.exposed.dao.id.IntIdTable

object AnalysisSessions : IntIdTable("analysis_session") {
    val name = text("name")
    val description = text("description").nullable()
    val topicQuery = text("topic_query")
    val region = text("region").nullable()
    val displayTimezone = text("display_timezone").default("Europe/Moscow")
    val baselineWindowDays = integer("baseline_window_days").default(60)
    val currentWindowDays = integer("current_window_days").default(30)
    val nlpMode = text("nlp_mode").default("FULL")
    val nlpModelVersions = text("nlp_model_versions").nullable()
    val referenceBaseVersion = text("reference_base_version").nullable()
    val referenceBaseSha256 = text("reference_base_sha256").nullable()
    val holidaysVersion = text("holidays_version").nullable()
    val sentilexVersion = text("sentilex_version").nullable()
    val testCorpusVersion = text("test_corpus_version").nullable()
    val gammaCalibrated = float("gamma_calibrated").nullable()
    val gammaClipped = bool("gamma_clipped").default(false)
    val gammaFallback = bool("gamma_fallback").default(false)
    val gammaR2Mad = float("gamma_r2_mad").nullable()
    val referenceGammaDivergenceFlag = text("reference_gamma_divergence_flag").default("OK")
    val roleThresholdBase = float("role_threshold_base").nullable()
    val roleThresholdEvent = float("role_threshold_event").nullable()
    val cvIqrJson = text("cv_iqr_json").nullable()
    val coverageRatio = float("coverage_ratio").nullable()
    val sessionQualityScore = float("session_quality_score").nullable()
    val qualityGatesJson = text("quality_gates_json").nullable()
    val normStatsJson = text("norm_stats_json").nullable()
    val status = text("status").default("CREATED")
    val sessionFamilyId = optReference("session_family_id", AnalysisSessions)
    val tOrthogonalized = bool("t_orthogonalized").default(false)
    val eventWeightsVariant = text("event_weights_variant").nullable()
    val possiblyNonStationaryFlag = bool("possibly_non_stationary_flag").default(false)
    val holidaysPartialCoverageFlag = bool("holidays_partial_coverage_flag").default(false)
    val seasonalityDisabledFlag = bool("seasonality_disabled_flag").default(false)
    val createdAt = long("created_at")
    val updatedAt = long("updated_at")
    val deletedAt = long("deleted_at").nullable()
}
