package com.example.lomanalyzer.storage.tables

import org.jetbrains.exposed.dao.id.IntIdTable

object LomScores : IntIdTable("lom_score") {
    val sessionId = reference("session_id", AnalysisSessions)
    val authorId = reference("author_id", Authors)
    val audienceNorm = float("audience_norm").nullable()
    val audienceCiLo = float("audience_ci_lo").nullable()
    val audienceCiHi = float("audience_ci_hi").nullable()
    val engagementDensityNorm = float("engagement_density_norm").nullable()
    val engagementDensityCiLo = float("engagement_density_ci_lo").nullable()
    val engagementDensityCiHi = float("engagement_density_ci_hi").nullable()
    val baseInfluenceHist = float("base_influence_hist").nullable()
    val baseInfluenceHistCiLo = float("base_influence_hist_ci_lo").nullable()
    val baseInfluenceHistCiHi = float("base_influence_hist_ci_hi").nullable()
    val baseInfluenceCurr = float("base_influence_curr").nullable()
    val baseInfluenceCurrCiLo = float("base_influence_curr_ci_lo").nullable()
    val baseInfluenceCurrCiHi = float("base_influence_curr_ci_hi").nullable()
    val baseInfluenceAbs = float("base_influence_abs").nullable()
    val baseInfluenceAbsCiLo = float("base_influence_abs_ci_lo").nullable()
    val baseInfluenceAbsCiHi = float("base_influence_abs_ci_hi").nullable()
    val eventActivityHist = float("event_activity_hist").nullable()
    val eventActivityHistCiLo = float("event_activity_hist_ci_lo").nullable()
    val eventActivityHistCiHi = float("event_activity_hist_ci_hi").nullable()
    val eventActivityCurr = float("event_activity_curr").nullable()
    val eventActivityCurrCiLo = float("event_activity_curr_ci_lo").nullable()
    val eventActivityCurrCiHi = float("event_activity_curr_ci_hi").nullable()
    val topicFocusRaw = float("topic_focus_raw").nullable()
    val topicVolumeNorm = float("topic_volume_norm").nullable()
    val disseminationReachNorm = float("dissemination_reach_norm").nullable()
    val contentOriginalityNorm = float("content_originality_norm").nullable()
    val kWindow = integer("k_window").nullable()
    val gammaUsed = float("gamma_used").nullable()
    val tOrthogonalized = bool("t_orthogonalized").default(false)
    val rOrthogonalizationMadR2 = float("r_orthogonalization_mad_r2").nullable()
    val roleSession = text("role_session").nullable()
    val roleReference = text("role_reference").nullable()
    val roleCombined = text("role_combined").nullable()
    val roleConfidence = float("role_confidence").nullable()
    val roleCombinationFlag = text("role_combination_flag").nullable()
    val createdAt = long("created_at")
}
