package com.example.lomanalyzer.storage.tables

import org.jetbrains.exposed.dao.id.IntIdTable

object PersonaAggregates : IntIdTable("persona_aggregate") {
    val authorId = reference("author_id", Authors)
    val sessionId = reference("session_id", AnalysisSessions)
    val snapshotTimestamp = long("snapshot_timestamp")
    val audience = float("audience").nullable()
    val audienceCiLo = float("audience_ci_lo").nullable()
    val audienceCiHi = float("audience_ci_hi").nullable()
    val engagementDensity = float("engagement_density").nullable()
    val engagementDensityCiLo = float("engagement_density_ci_lo").nullable()
    val engagementDensityCiHi = float("engagement_density_ci_hi").nullable()
    val iBaseHist = float("i_base_hist").nullable()
    val iBaseHistCiLo = float("i_base_hist_ci_lo").nullable()
    val iBaseHistCiHi = float("i_base_hist_ci_hi").nullable()
    val iBaseCurr = float("i_base_curr").nullable()
    val iBaseCurrCiLo = float("i_base_curr_ci_lo").nullable()
    val iBaseCurrCiHi = float("i_base_curr_ci_hi").nullable()
    val iBaseAbs = float("i_base_abs").nullable()
    val iBaseAbsCiLo = float("i_base_abs_ci_lo").nullable()
    val iBaseAbsCiHi = float("i_base_abs_ci_hi").nullable()
    val iEventHist = float("i_event_hist").nullable()
    val iEventHistCiLo = float("i_event_hist_ci_lo").nullable()
    val iEventHistCiHi = float("i_event_hist_ci_hi").nullable()
    val iEventCurr = float("i_event_curr").nullable()
    val iEventCurrCiLo = float("i_event_curr_ci_lo").nullable()
    val iEventCurrCiHi = float("i_event_curr_ci_hi").nullable()
    val roleSession = text("role_session").nullable()
    val roleReference = text("role_reference").nullable()
    val roleCombined = text("role_combined").nullable()
    val roleConfidence = float("role_confidence").nullable()
    val roleCombinationFlag = text("role_combination_flag").nullable()
    val totalPosts = integer("total_posts").nullable()
    val topicPostsEff = float("topic_posts_eff").nullable()
    val topicFocusRaw = float("topic_focus_raw").nullable()
    val topicVolumeNorm = float("topic_volume_norm").nullable()
    val disseminationReachNorm = float("dissemination_reach_norm").nullable()
    val originalityNorm = float("originality_norm").nullable()
    val avgSentimentHuber = float("avg_sentiment_huber").nullable()
    val avgSentimentHuberCiLo = float("avg_sentiment_huber_ci_lo").nullable()
    val avgSentimentHuberCiHi = float("avg_sentiment_huber_ci_hi").nullable()
    val sentimentUnstableRatio = float("sentiment_unstable_ratio").nullable()
    val authorToneMixedFlag = bool("author_tone_mixed_flag").default(false)
    val visualActivityRatio = float("visual_activity_ratio").nullable()
    val topTerms = text("top_terms").nullable()
    val accountFlags = text("account_flags").nullable()
    val firstSeenAt = long("first_seen_at").nullable()
    val lastSeenAt = long("last_seen_at").nullable()
    val anomalyParticipation = text("anomaly_participation").nullable()
    val discoverySource = text("discovery_source").nullable()
    val baselineWindowDays = integer("baseline_window_days").nullable()
    val kWindow = integer("k_window").nullable()
    val gammaUsed = float("gamma_used").nullable()
    val gammaDivergenceFlag = text("gamma_divergence_flag").nullable()
    val tOrthogonalized = bool("t_orthogonalized").default(false)
    val possiblyNonStationaryFlag = bool("possibly_non_stationary_flag").default(false)
}
